package markdown

import (
	"bytes"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/messeb/escpos-cli/internal/escpos"
	"github.com/yuin/goldmark/ast"
	extast "github.com/yuin/goldmark/extension/ast"
	"github.com/yuin/goldmark/renderer"
	"github.com/yuin/goldmark/util"
)

// ESCPOSRenderer renders Goldmark AST to ESC/POS commands
type ESCPOSRenderer struct {
	buf            *bytes.Buffer
	listDepth      int
	listCounters   []int // Stack of counters for ordered lists
	inBold         bool
	inEmphasis     bool
	currentAlign   int // 0=left, 1=center, 2=right
	markdownDir    string
	imageThreshold int
	currentColumn  int  // Current column position for word wrapping
	afterLineBreak bool // Track if we just wrote a <br> to skip leading space
}

// NewESCPOSRenderer creates a new ESCPOSRenderer
func NewESCPOSRenderer(markdownDir string, threshold int) *ESCPOSRenderer {
	return &ESCPOSRenderer{
		buf:            &bytes.Buffer{},
		listDepth:      0,
		listCounters:   []int{},
		inBold:         false,
		inEmphasis:     false,
		currentAlign:   0,
		markdownDir:    markdownDir,
		imageThreshold: threshold,
		currentColumn:  0,
		afterLineBreak: false,
	}
}

// Render renders the AST to ESC/POS
func (r *ESCPOSRenderer) Render(w util.BufWriter, source []byte, node ast.Node) error {
	// Initialize printer
	r.buf.Write(escpos.Init())
	r.buf.Write(escpos.LineFeed())
	r.buf.Write(escpos.LineFeed())

	// Walk the AST
	err := ast.Walk(node, func(n ast.Node, entering bool) (ast.WalkStatus, error) {
		return r.renderNode(n, entering, source)
	})

	if err != nil {
		return err
	}

	// Finalize - feed and cut
	r.buf.Write(escpos.Init())
	r.buf.Write(escpos.Feed(5))
	r.buf.Write(escpos.Cut())

	// Write to output
	_, err = w.Write(r.buf.Bytes())
	return err
}

// AddOptions adds renderer options (required by renderer.Renderer interface)
func (r *ESCPOSRenderer) AddOptions(...renderer.Option) {
	// No options needed for ESC/POS
}

// renderNode renders a single AST node
func (r *ESCPOSRenderer) renderNode(n ast.Node, entering bool, source []byte) (ast.WalkStatus, error) {
	switch n.Kind() {
	case ast.KindDocument:
		// Nothing special for document
		return ast.WalkContinue, nil

	case ast.KindHeading:
		return r.renderHeading(n.(*ast.Heading), entering)

	case ast.KindParagraph:
		return r.renderParagraph(n.(*ast.Paragraph), entering)

	case ast.KindText:
		if entering {
			return r.renderText(n.(*ast.Text), source)
		}
		return ast.WalkSkipChildren, nil

	case ast.KindString:
		if entering {
			return r.renderString(n.(*ast.String))
		}
		return ast.WalkSkipChildren, nil

	case ast.KindEmphasis:
		return r.renderEmphasis(n.(*ast.Emphasis), entering)

	case ast.KindList:
		return r.renderList(n.(*ast.List), entering)

	case ast.KindListItem:
		return r.renderListItem(n.(*ast.ListItem), entering)

	case ast.KindImage:
		return r.renderImage(n.(*ast.Image), source, entering)

	case ast.KindCodeBlock, ast.KindFencedCodeBlock:
		// Regular code blocks are skipped (we handle barcodes separately)
		return ast.WalkSkipChildren, nil

	case ast.KindThematicBreak:
		return r.renderThematicBreak(entering)

	case ast.KindHTMLBlock:
		// Handle HTML blocks (including <br>)
		return r.renderHTMLBlock(n.(*ast.HTMLBlock), source, entering)

	case ast.KindRawHTML:
		// Handle inline HTML (including <br>)
		return r.renderRawHTML(n.(*ast.RawHTML), source, entering)

	case ast.KindAutoLink:
		// Handle autolinks (email addresses, URLs generated by GFM)
		return r.renderAutoLink(n.(*ast.AutoLink), source, entering)

	case extast.KindTaskCheckBox:
		return r.renderTaskCheckBox(n.(*extast.TaskCheckBox), entering)

	case extast.KindTable:
		return r.renderTable(n.(*extast.Table), source, entering)

	case extast.KindTableHeader, extast.KindTableRow, extast.KindTableCell:
		// These are handled by renderTable
		return ast.WalkContinue, nil

	default:
		// Check if it's a custom barcode block using type assertion
		if barcode, ok := n.(*BarcodeBlock); ok {
			return r.renderBarcodeBlock(barcode, entering)
		}
		// Skip unknown nodes
		return ast.WalkContinue, nil
	}
}

// renderHeading renders a heading
func (r *ESCPOSRenderer) renderHeading(n *ast.Heading, entering bool) (ast.WalkStatus, error) {
	if entering {
		// Reset formatting
		r.buf.Write(escpos.AlignCenter())
		r.buf.Write(escpos.BoldOn())

		// Set size based on level
		switch n.Level {
		case 1:
			r.buf.Write(escpos.DoubleSize()) // H1: double width and height
		case 2:
			r.buf.Write(escpos.DoubleHeight()) // H2: double height
		case 3:
			r.buf.Write(escpos.DoubleWidth()) // H3: double width
		default:
			r.buf.Write(escpos.NormalSize())
		}

		r.currentAlign = 1
		r.inBold = true
	} else {
		// Reset after heading
		r.buf.Write(escpos.LineFeed())
		r.buf.Write(escpos.NormalSize())
		r.buf.Write(escpos.BoldOff())
		r.buf.Write(escpos.AlignLeft())
		r.buf.Write(escpos.LineFeed())
		r.resetColumn()

		r.currentAlign = 0
		r.inBold = false
	}

	return ast.WalkContinue, nil
}

// renderParagraph renders a paragraph
func (r *ESCPOSRenderer) renderParagraph(n *ast.Paragraph, entering bool) (ast.WalkStatus, error) {
	if !entering {
		r.buf.Write(escpos.LineFeed())
		r.resetColumn()
		// Don't add extra line feed if inside a list item
		if _, ok := n.Parent().(*ast.ListItem); !ok {
			r.buf.Write(escpos.LineFeed())
		}
	}
	return ast.WalkContinue, nil
}

// renderText renders text content
func (r *ESCPOSRenderer) renderText(n *ast.Text, source []byte) (ast.WalkStatus, error) {
	segment := n.Segment
	text := string(segment.Value(source))

	// Always strip leading whitespace when at the start of a line (column 0)
	// This handles cases where text is split into multiple nodes after a <br>
	if r.currentColumn == 0 && len(text) > 0 {
		text = strings.TrimLeft(text, " \t\n\r")
	}

	// Write text with proper line wrapping (46 chars for thermal printer)
	r.writeWrappedText(text)

	// Skip soft line break handling - we handle wrapping ourselves in writeWrappedText
	// Adding spaces for soft line breaks interferes with explicit <br> tags
	// if n.SoftLineBreak() {
	// 	r.buf.WriteByte(' ')
	// }

	// Text nodes are leaf nodes, skip children
	return ast.WalkSkipChildren, nil
}

// renderString renders a string node
func (r *ESCPOSRenderer) renderString(n *ast.String) (ast.WalkStatus, error) {
	r.writeWrappedText(string(n.Value))
	// String nodes are leaf nodes, skip children
	return ast.WalkSkipChildren, nil
}

// renderEmphasis renders emphasis (bold or italic)
func (r *ESCPOSRenderer) renderEmphasis(n *ast.Emphasis, entering bool) (ast.WalkStatus, error) {
	if entering {
		if n.Level == 2 {
			// Strong (**text**) -> bold
			r.buf.Write(escpos.BoldOn())
			r.inBold = true
		} else {
			// Emphasis (*text*) -> underline (thermal printers don't have italic)
			r.buf.Write(escpos.UnderlineOn())
			r.inEmphasis = true
		}
	} else {
		if n.Level == 2 {
			r.buf.Write(escpos.BoldOff())
			r.inBold = false
		} else {
			r.buf.Write(escpos.UnderlineOff())
			r.inEmphasis = false
		}
	}
	return ast.WalkContinue, nil
}

// renderList renders a list
func (r *ESCPOSRenderer) renderList(n *ast.List, entering bool) (ast.WalkStatus, error) {
	if entering {
		r.listDepth++
		if n.IsOrdered() {
			r.listCounters = append(r.listCounters, n.Start)
		} else {
			r.listCounters = append(r.listCounters, 0)
		}
	} else {
		r.listDepth--
		if len(r.listCounters) > 0 {
			r.listCounters = r.listCounters[:len(r.listCounters)-1]
		}
		if r.listDepth == 0 {
			r.buf.Write(escpos.LineFeed())
			r.resetColumn()
		}
	}
	return ast.WalkContinue, nil
}

// renderListItem renders a list item
func (r *ESCPOSRenderer) renderListItem(n *ast.ListItem, entering bool) (ast.WalkStatus, error) {
	if entering {
		// Check if this is a task list item (has TaskCheckBox child)
		hasTaskCheckBox := false
		for child := n.FirstChild(); child != nil; child = child.NextSibling() {
			if child.Kind() == extast.KindTaskCheckBox {
				hasTaskCheckBox = true
				break
			}
		}

		// Add indentation based on depth
		indent := strings.Repeat("  ", r.listDepth-1)
		r.buf.WriteString(indent)
		r.currentColumn = len(indent)

		// Don't add bullet/number for task list items (they have checkboxes)
		if !hasTaskCheckBox {
			// Determine marker
			parent := n.Parent().(*ast.List)
			if parent.IsOrdered() {
				// Ordered list - use number
				counter := r.listCounters[len(r.listCounters)-1]
				marker := fmt.Sprintf("%d. ", counter)
				r.buf.WriteString(marker)
				r.currentColumn += len(marker)
				r.listCounters[len(r.listCounters)-1]++
			} else {
				// Unordered list - use ASCII characters instead of Unicode
				var marker string
				switch r.listDepth {
				case 1:
					marker = "- "
				case 2:
					marker = "  * "
				default:
					marker = "    + "
				}
				r.buf.WriteString(marker)
				r.currentColumn += len(marker)
			}
		}
	} else {
		// Add line feed after list item
		r.buf.Write(escpos.LineFeed())
		r.resetColumn()
	}
	return ast.WalkContinue, nil
}

// renderImage renders an image
func (r *ESCPOSRenderer) renderImage(n *ast.Image, source []byte, entering bool) (ast.WalkStatus, error) {
	if !entering {
		return ast.WalkSkipChildren, nil
	}

	// Get image path
	imagePath := string(n.Destination)

	// Resolve relative paths
	if !filepath.IsAbs(imagePath) {
		imagePath = filepath.Join(r.markdownDir, imagePath)
	}

	// Convert image to ESC/POS
	imgData, err := escpos.ConvertImageToESCPOS(imagePath, r.imageThreshold)
	if err != nil {
		// Error handling: print error message instead of crashing
		fmt.Fprintf(r.buf, "[Image error: %s]\n", err.Error())
	} else {
		r.buf.Write(imgData)
	}

	return ast.WalkSkipChildren, nil
}

// renderThematicBreak renders a horizontal rule
func (r *ESCPOSRenderer) renderThematicBreak(entering bool) (ast.WalkStatus, error) {
	if entering {
		// Use bitmap to create a true solid line (no gaps)
		// 46 chars * 12 pixels/char = 552 pixels (matches text width)
		r.buf.Write(escpos.SolidLine(552))
		r.buf.Write(escpos.LineFeed())
		r.resetColumn()
	}
	return ast.WalkSkipChildren, nil
}

// renderHTMLBlock renders HTML block elements
func (r *ESCPOSRenderer) renderHTMLBlock(n *ast.HTMLBlock, source []byte, entering bool) (ast.WalkStatus, error) {
	if !entering {
		return ast.WalkSkipChildren, nil
	}

	// Check if it's a <br> tag
	for i := 0; i < n.Lines().Len(); i++ {
		line := n.Lines().At(i)
		text := string(line.Value(source))
		if strings.Contains(strings.ToLower(text), "<br") {
			r.buf.Write(escpos.LineFeed())
			r.resetColumn()
			r.afterLineBreak = true
		}
	}

	return ast.WalkSkipChildren, nil
}

// renderRawHTML renders inline HTML elements
func (r *ESCPOSRenderer) renderRawHTML(n *ast.RawHTML, source []byte, entering bool) (ast.WalkStatus, error) {
	if !entering {
		return ast.WalkContinue, nil
	}

	// Process HTML segments
	for i := 0; i < n.Segments.Len(); i++ {
		segment := n.Segments.At(i)
		text := string(segment.Value(source))
		lowerText := strings.ToLower(text)

		// Handle <br> tags
		if strings.Contains(lowerText, "<br") {
			r.buf.Write(escpos.LineFeed())
			r.resetColumn()
			r.afterLineBreak = true
			continue
		}

		// For other HTML tags, we'll let the child text nodes be processed
		// by returning WalkContinue, which allows the AST walker to visit children
	}

	return ast.WalkContinue, nil
}

// renderAutoLink renders autolinks (email addresses and URLs detected by GFM)
func (r *ESCPOSRenderer) renderAutoLink(n *ast.AutoLink, source []byte, entering bool) (ast.WalkStatus, error) {
	if !entering {
		return ast.WalkSkipChildren, nil
	}

	// Extract and render the link label (the display text)
	label := string(n.Label(source))
	r.writeWrappedText(label)

	return ast.WalkSkipChildren, nil
}

// renderTaskCheckBox renders a task list checkbox
func (r *ESCPOSRenderer) renderTaskCheckBox(n *extast.TaskCheckBox, entering bool) (ast.WalkStatus, error) {
	if entering {
		if n.IsChecked {
			r.buf.WriteString("[x] ")
			r.currentColumn += 4
		} else {
			r.buf.WriteString("[ ] ")
			r.currentColumn += 4
		}
	}
	return ast.WalkContinue, nil
}

// renderBarcodeBlock renders a custom barcode block
func (r *ESCPOSRenderer) renderBarcodeBlock(n *BarcodeBlock, entering bool) (ast.WalkStatus, error) {
	if !entering {
		return ast.WalkSkipChildren, nil
	}

	// Generate barcode based on type
	var barcodeData []byte

	switch n.BarcodeType {
	case BarcodeQR:
		barcodeData = escpos.GenerateQRCode(n.Data)
	case BarcodePDF417:
		barcodeData = escpos.GeneratePDF417(n.Data)
	case BarcodeDataMatrix:
		barcodeData = escpos.GenerateDataMatrix(n.Data)
	case BarcodeEAN13:
		barcodeData = escpos.GenerateEAN13(n.Data)
	default:
		fmt.Fprintf(r.buf, "[Unknown barcode type: %d]\n", n.BarcodeType)
		return ast.WalkSkipChildren, nil
	}

	r.buf.Write(barcodeData)
	r.buf.Write(escpos.LineFeed())
	r.resetColumn()

	return ast.WalkSkipChildren, nil
}

// renderTable renders a table
func (r *ESCPOSRenderer) renderTable(n *extast.Table, source []byte, entering bool) (ast.WalkStatus, error) {
	if !entering {
		return ast.WalkSkipChildren, nil
	}

	// Create table renderer
	tableRenderer := NewTableRenderer()
	tableRenderer.ExtractTableData(n, source)

	// Render table
	tableData := tableRenderer.Render()
	r.buf.Write(tableData)
	r.buf.Write(escpos.LineFeed())
	r.resetColumn()

	return ast.WalkSkipChildren, nil
}

// writeWrappedText writes text with word wrapping at 46 characters
// Words are not broken in the middle - wrapping happens at word boundaries
// Tracks column position across multiple calls to handle formatted text correctly
func (r *ESCPOSRenderer) writeWrappedText(text string) {
	const maxWidth = 46 // Thermal printer width in characters

	// If text is empty, nothing to do
	if len(text) == 0 {
		return
	}

	// Split into words
	words := strings.Fields(text)
	if len(words) == 0 {
		return
	}

	for _, word := range words {
		wordLen := len(word)

		// Check if adding this word would exceed the line width
		spaceNeeded := 0
		if r.currentColumn > 0 {
			spaceNeeded = 1 // Space before word
		}

		if r.currentColumn+spaceNeeded+wordLen > maxWidth {
			// Current line is full, start a new line
			r.buf.WriteByte(0x0D) // CR - return to column 0
			r.buf.WriteByte(0x0A) // LF - move to next line
			r.currentColumn = 0
			spaceNeeded = 0 // No space needed at start of new line
		}

		// Add space before word if not at start of line
		if r.currentColumn > 0 {
			r.buf.WriteByte(' ')
			r.currentColumn++
		}

		// Write the word
		r.buf.WriteString(word)
		r.currentColumn += wordLen

		// If word itself was longer than max width, start new line
		if wordLen > maxWidth {
			r.buf.WriteByte(0x0D) // CR - return to column 0
			r.buf.WriteByte(0x0A) // LF - move to next line
			r.currentColumn = 0
		}
	}
}

// resetColumn resets the current column position (called after explicit line breaks)
func (r *ESCPOSRenderer) resetColumn() {
	r.currentColumn = 0
}
